### ISSUE TITLE
riddl requires fully qualified path names

### ISSUE THREAD

**Issue by JamesYopp** [ossuminc/riddl#480] opened 2023-11-17 03:07 UTC
When specifying the kso template app riddl required me to provide fully qualified path names. The project is effectively empty so there are no name conflicts at this point. Consider the following specification:

```
type SignupParameters is {
  firstName: String,
  lastName: String,
  emailAddress: ksoTemplateAppDomain.EmailAddress,
  password: String
}

type FirstName: String
type LastName: String
type Password: String

command CreateUser is {user: ksoTemplateAppDomain.ksoTemplateApp.SignupParameters}
command CreateUserUsingFacebook is {???}
command CreateUserUsingGitHub is {???}
command CreateUserUsingGmail is {???}
command RedirectUserToSigninPage is {???}

page SignupPage {
  form NewUserForm is {
    input firstName accepts ksoTemplateAppDomain.ksoTemplateApp.FirstName
    input lastName accepts ksoTemplateAppDomain.ksoTemplateApp.LastName
    input emailAddress accepts ksoTemplateAppDomain.EmailAddress
    input password accepts ksoTemplateAppDomain.ksoTemplateApp.Password
  }
  button SignupButton initiates command ksoTemplateAppDomain.ksoTemplateApp.CreateUser
  button FacebookSignupButton initiates command ksoTemplateAppDomain.ksoTemplateApp.CreateUserUsingFacebook
  button GitHubSignupButton initiates command ksoTemplateAppDomain.ksoTemplateApp.CreateUserUsingGitHub
  button GmailSignupButton initiates command ksoTemplateAppDomain.ksoTemplateApp.CreateUserUsingGmail
  text SigninLink takes command ksoTemplateAppDomain.ksoTemplateApp.RedirectUserToSigninPage
}

```

SignupParameters is defined in this file only, but in order for riddl to validate it required the full path. The error that I got when compiling is as follows:
```
[error] Error: application/pages/signup.riddl(12:30):
Path reference 'SignupParameters' is ambiguous. Definitions are:
  ksoTemplateAppDomain.ksoTemplateApp.SignupParameters (signup.riddl(1:1))
  ksoTemplateAppDomain.ksoTemplateApp..SignupParameters (signup.riddl(1:1)):
command CreateUser is {user: SignupParameters}
                             ^
```

**Comment by reid-spencer** [comment] 2023-11-17 14:10
The puzzling things about this is the two things it thinks are different, reported as:
```shell
ksoTemplateAppDomain.ksoTemplateApp.SignupParameters (signup.riddl(1:1))
ksoTemplateAppDomain.ksoTemplateApp..SignupParameters (signup.riddl(1:1)):
```
Note the  `.` versus the `..` following ` ksoTemplateApp`. Its like the second one has an empty element in the PathIdentifier

**Comment by JamesYopp** [comment] 2023-11-17 14:29
Another clue to the puzzle may be that when this error occurs it appears in the terminal 4 times - all error text is exactly the same output.

**Comment by JamesYopp** [comment] 2023-11-17 14:31
It also might be worth noting that this error was generated in riddl version `0.27.5-1-88ab7cbf-SNAPSHOT`

**Comment by reid-spencer** [comment] 2023-11-17 18:18
> It also might be worth noting that this error was generated in riddl version `0.27.5-1-88ab7cbf-SNAPSHOT`

I think this is the problem. My current local version is 0.27.5-2-... so you might need to upgrade and try one more time. 

My first attempt to reproduce didn't. It parsed and resolved just fine. I then used your full text and got it to not parse because of the incorrect syntax on the form. More details on that when I have it corrected.

**Comment by reid-spencer** [comment] 2023-11-17 18:30
@JamesYopp - I've added a test case.  It succeeds with the resolution pass after I fixed a syntax error in your input. I'm not sure why it didn't show for you.   I also need to know the exact arguments to riddlc that you used to get the error reported.

**Comment by reid-spencer** [comment] 2023-11-17 21:08
James reported this command:
`riddlc from design/src/main/riddl/ksoapp.conf validate`

**Comment by reid-spencer** [comment] 2023-12-11 22:50
Reopening because an instance of the same error message showed up in HEAD of main

**Comment by reid-spencer** [comment] 2023-12-13 00:49
Fixed by never placing implicit definitions in the symbol table

**Comment by reid-spencer** [comment] 2023-12-13 15:23
This should be fixed now.

**Closed by reid-spencer** 2023-12-13 15:23 UTC
Labels: bug
